package com.techcircle.moodyz;

import com.techcircle.moodyz.config.AppConfig;
import com.techcircle.moodyz.constants.RouteConstants;
import com.techcircle.moodyz.utils.GUIStyler;
import com.techcircle.moodyz.utils.IconBuilder;
import com.techcircle.moodyz.utils.Animation;
import com.techcircle.moodyz.app.views.components.InPlayingSong;
import com.techcircle.moodyz.app.views.components.layouts.MainLayout;
import org.jdesktop.core.animation.timing.Animator;
import org.jdesktop.core.animation.timing.TimingSource;
import org.jdesktop.swing.animation.timing.sources.SwingTimerTimingSource;
import org.kordamp.ikonli.fontawesome5.FontAwesomeRegular;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gica Tran
 */
public class MoodyZApplication extends JFrame {
    private AppConfig appConfig;
    private TimingSource timingSource;
    private Animation animation;
    private GUIStyler guiStyler;
    private Rectangle normalBounds;

    private boolean maximize;
    private int pX;
    private int pY;

    public MoodyZApplication() {
        initApp();
        initRoutes();

        initComponents();
        initForm();
    }
    
    private void initApp() {
        appConfig = new AppConfig(this);
        guiStyler = new GUIStyler();

        appConfig.init();
    }

    private void initRoutes() {
        appConfig.use(RouteConstants.HOME);
        appConfig.use(RouteConstants.SEARCH);

        appConfig.setDefault(RouteConstants.HOME);
    }

    private void initForm() {
        timingSource = new SwingTimerTimingSource();
        animation = new Animation(timingSource);

        Animator.setDefaultTimingSource(timingSource);
        timingSource.init();

        btnMinimize.setIcon(new IconBuilder().prepareIcon(FontAwesomeRegular.WINDOW_MINIMIZE, btnMinimize.getHeight() / 4, Color.WHITE));
        btnMaximize.setIcon(new IconBuilder().prepareIcon(FontAwesomeRegular.WINDOW_MAXIMIZE, btnMaximize.getHeight() / 3, Color.WHITE));
        btnClose.setIcon(new IconBuilder().prepareIcon(FontAwesomeSolid.TIMES, btnClose.getHeight() / 3, Color.WHITE));
        btnMore.setIcon(new IconBuilder().prepareIcon(FontAwesomeSolid.ELLIPSIS_H, btnMore.getHeight() / 2, Color.WHITE));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border = new JPanel();
        background = new JPanel();
        titleBar = new JPanel();
        btnMinimize = new JButton();
        btnMaximize = new JButton();
        btnClose = new JButton();
        btnMore = new JButton();
        body = new JLayeredPane();
        mainLayout = new MainLayout();
        inPlayingSong = new InPlayingSong();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new Dimension(1366, 768));

        border.setBackground(new Color(30, 30, 30));
        border.setPreferredSize(new Dimension(1366, 768));

        background.setBackground(new Color(0, 0, 0));
        background.setPreferredSize(new Dimension(1366, 768));

        titleBar.setBackground(new Color(0, 0, 0));
        titleBar.setPreferredSize(new Dimension(1366, 30));
        titleBar.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        btnMinimize.setBorder(null);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        btnMinimize.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        btnMaximize.setBorder(null);
        btnMaximize.setContentAreaFilled(false);
        btnMaximize.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                btnMaximizeMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                btnMaximizeMouseExited(evt);
            }
        });
        btnMaximize.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnMaximizeActionPerformed(evt);
            }
        });

        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnMore.setBorder(null);
        btnMore.setContentAreaFilled(false);
        btnMore.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnMoreActionPerformed(evt);
            }
        });

        GroupLayout titleBarLayout = new GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMore, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMaximize, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClose, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(btnMaximize, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMore, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClose, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        body.setLayout(new BorderLayout());
        body.add(mainLayout, BorderLayout.CENTER);

        GroupLayout backgroundLayout = new GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(body, GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
            .addComponent(inPlayingSong, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(titleBar, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(inPlayingSong, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE))
        );

        GroupLayout borderLayout = new GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(background, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(background, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(border, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(border, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        close();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMaximizeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnMaximizeActionPerformed
        toggleMaximize();
    }//GEN-LAST:event_btnMaximizeActionPerformed

    private void btnMinimizeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        minimize();
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void titleBarMouseDragged(MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - pX, this.getLocation().y + evt.getY() - pY);
    }//GEN-LAST:event_titleBarMouseDragged

    private void titleBarMousePressed(MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        pX = evt.getX();
        pY = evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void btnCloseMouseEntered(MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        guiStyler.setHoverBgColor(btnClose, Color.RED);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        guiStyler.removeHoverBgColor(btnClose);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMaximizeMouseEntered(MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseEntered
        guiStyler.setHoverBgColor(btnMaximize, Color.DARK_GRAY);
    }//GEN-LAST:event_btnMaximizeMouseEntered

    private void btnMaximizeMouseExited(MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseExited
        guiStyler.removeHoverBgColor(btnMaximize);
    }//GEN-LAST:event_btnMaximizeMouseExited

    private void btnMinimizeMouseEntered(MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        guiStyler.setHoverBgColor(btnMinimize, Color.DARK_GRAY);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        guiStyler.removeHoverBgColor(btnMinimize);
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnMoreActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnMoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoreActionPerformed

    private void close() {
        animation.fadeOut(this, () -> System.exit(0));
    }

    private void toggleMaximize() {
        if (maximize) {
            setBounds(normalBounds);
            btnMaximize.setIcon(new IconBuilder().prepareIcon(FontAwesomeRegular.WINDOW_RESTORE, btnMaximize.getHeight(), Color.WHITE));
            maximize = false;
        }
        else {
            normalBounds = getBounds();
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            btnMaximize.setIcon(new IconBuilder().prepareIcon(FontAwesomeRegular.WINDOW_MAXIMIZE, btnMaximize.getHeight(), Color.WHITE));
            maximize = true;
        }
    }

    private void minimize() {
        animation.fadeOut(this, () -> setState(JFrame.ICONIFIED));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MoodyZApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> {
            new MoodyZApplication().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel background;
    private JLayeredPane body;
    private JPanel border;
    private JButton btnClose;
    private JButton btnMaximize;
    private JButton btnMinimize;
    private JButton btnMore;
    private InPlayingSong inPlayingSong;
    private MainLayout mainLayout;
    private JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
