package com.techcircle.moodyz;

import com.techcircle.moodyz.app.views.components.InPlayingSong;
import com.techcircle.moodyz.config.AppConfig;
import com.techcircle.moodyz.utils.IconBuilder;
import com.techcircle.moodyz.utils.Animation;
import org.jdesktop.core.animation.timing.Animator;
import org.jdesktop.core.animation.timing.TimingSource;
import org.jdesktop.swing.animation.timing.sources.SwingTimerTimingSource;
import org.kordamp.ikonli.fontawesome5.FontAwesomeRegular;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gica Tran
 */
public class MoodyZApplication extends JFrame {
    private AppConfig appConfig;
    private TimingSource timingSource;
    private Animation animation;
    private Rectangle normalBounds;

    private boolean maximize;
    private boolean morePopup;
    private int pX;
    private int pY;

    public MoodyZApplication() {
        initApp();

        initComponents();
        initForm();
    }
    
    private void initApp() {
        appConfig = new AppConfig(this);

        appConfig.init();
    }

    private void initForm() {
        timingSource = new SwingTimerTimingSource();
        animation = new Animation(timingSource);

        Animator.setDefaultTimingSource(timingSource);
        timingSource.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMore = new javax.swing.JPopupMenu();
        menuFile = new javax.swing.JMenu();
        itemNew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemLogout = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        border = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        btnClose = new com.techcircle.moodyz.app.views.components.global.CustomButton();
        btnMaximize = new com.techcircle.moodyz.app.views.components.global.CustomButton();
        btnMinimize = new com.techcircle.moodyz.app.views.components.global.CustomButton();
        btnMore = new com.techcircle.moodyz.app.views.components.global.CustomButton();
        body = new javax.swing.JLayeredPane();
        mainLayout = new com.techcircle.moodyz.app.views.components.layouts.MainLayout();
        inPlayingSong = new InPlayingSong();

        menuFile.setText("File");

        itemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemNew.setText("New Playlist");
        itemNew.setContentAreaFilled(false);
        itemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNewActionPerformed(evt);
            }
        });
        menuFile.add(itemNew);
        menuFile.add(jSeparator1);

        itemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemLogout.setText("Log Out");
        menuFile.add(itemLogout);
        menuFile.add(jSeparator2);

        itemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemExit.setText("Exit");
        menuFile.add(itemExit);

        popupMore.add(menuFile);

        menuEdit.setText("Edit");
        popupMore.add(menuEdit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));

        border.setBackground(new java.awt.Color(30, 30, 30));
        border.setPreferredSize(new java.awt.Dimension(1366, 768));

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setPreferredSize(new java.awt.Dimension(1366, 768));

        titleBar.setBackground(new java.awt.Color(0, 0, 0));
        titleBar.setPreferredSize(new java.awt.Dimension(1366, 30));
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(0, 0, 0));
        btnClose.setBorder(null);
        btnClose.setIcon(new IconBuilder(FontAwesomeSolid.TIMES, 15, Color.WHITE).prepareIcon());
        btnClose.setHoverColor(new java.awt.Color(196, 43, 28));
        btnClose.setPressedColor(new java.awt.Color(148, 19, 32));
        btnClose.setPressedIcon(new IconBuilder(FontAwesomeSolid.TIMES, 15, Color.WHITE).prepareIcon());
        btnClose.setRadius(0);
        btnClose.setRolloverIcon(new IconBuilder(FontAwesomeSolid.TIMES, 15, Color.WHITE).prepareIcon());
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnMaximize.setBackground(new java.awt.Color(0, 0, 0));
        btnMaximize.setBorder(null);
        btnMaximize.setIcon(new IconBuilder(FontAwesomeRegular.WINDOW_MAXIMIZE, 15, Color.WHITE).prepareIcon());
        btnMaximize.setHoverColor(new java.awt.Color(63, 63, 63));
        btnMaximize.setPressedColor(new java.awt.Color(51, 51, 51));
        btnMaximize.setPressedIcon(new IconBuilder(FontAwesomeRegular.WINDOW_MAXIMIZE, 15, Color.WHITE).prepareIcon());
        btnMaximize.setRadius(0);
        btnMaximize.setRolloverIcon(new IconBuilder(FontAwesomeRegular.WINDOW_MAXIMIZE, 15, Color.WHITE).prepareIcon());
        btnMaximize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizeActionPerformed(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimize.setBorder(null);
        btnMinimize.setIcon(new IconBuilder(FontAwesomeRegular.WINDOW_MINIMIZE, 10, Color.WHITE).prepareIcon());
        btnMinimize.setHoverColor(new java.awt.Color(63, 63, 63));
        btnMinimize.setPressedColor(new java.awt.Color(51, 51, 51));
        btnMinimize.setPressedIcon(new IconBuilder(FontAwesomeRegular.WINDOW_MINIMIZE, 10, Color.WHITE).prepareIcon());
        btnMinimize.setRadius(0);
        btnMinimize.setRolloverIcon(new IconBuilder(FontAwesomeRegular.WINDOW_MINIMIZE, 10, Color.WHITE).prepareIcon());
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        btnMore.setBackground(new java.awt.Color(0, 0, 0));
        btnMore.setIcon(new IconBuilder(FontAwesomeSolid.ELLIPSIS_H, 20, Color.WHITE).prepareIcon());
        btnMore.setHoverColor(new java.awt.Color(0, 0, 0));
        btnMore.setPressedColor(new java.awt.Color(0, 0, 0));
        btnMore.setPressedIcon(new IconBuilder(FontAwesomeSolid.ELLIPSIS_H, 20, Color.WHITE).prepareIcon());
        btnMore.setRadius(0);
        btnMore.setRolloverIcon(new IconBuilder(FontAwesomeSolid.ELLIPSIS_H, 20, Color.WHITE).prepareIcon());
        btnMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMaximize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMore, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        body.setLayout(new java.awt.BorderLayout());
        body.add(mainLayout, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
            .addComponent(inPlayingSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(inPlayingSong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(border, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(border, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void titleBarMouseDragged(MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - pX, this.getLocation().y + evt.getY() - pY);
    }//GEN-LAST:event_titleBarMouseDragged

    private void titleBarMousePressed(MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        pX = evt.getX();
        pY = evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        minimize();
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnMaximizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizeActionPerformed
        toggleMaximize();
    }//GEN-LAST:event_btnMaximizeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        close();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreActionPerformed
        toggleSettings();
    }//GEN-LAST:event_btnMoreActionPerformed

    private void itemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNewActionPerformed

    private void close() {
        animation.fadeOut(this, () -> System.exit(0));
    }

    private void toggleMaximize() {
        if (maximize) {
            setBounds(normalBounds);
            btnMaximize.setIcon(new IconBuilder(FontAwesomeRegular.WINDOW_MAXIMIZE, 15, Color.WHITE).prepareIcon());
            btnMaximize.setRolloverIcon(new IconBuilder(FontAwesomeRegular.WINDOW_MAXIMIZE, 15, Color.WHITE).prepareIcon());
            btnMaximize.setPressedIcon(new IconBuilder(FontAwesomeRegular.WINDOW_MAXIMIZE, 15, Color.WHITE).prepareIcon());
            maximize = false;
        }
        else {
            normalBounds = getBounds();
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            btnMaximize.setIcon(new IconBuilder(FontAwesomeRegular.WINDOW_RESTORE, 15, Color.WHITE).prepareIcon());
            btnMaximize.setRolloverIcon(new IconBuilder(FontAwesomeRegular.WINDOW_RESTORE, 15, Color.WHITE).prepareIcon());
            btnMaximize.setPressedIcon(new IconBuilder(FontAwesomeRegular.WINDOW_RESTORE, 15, Color.WHITE).prepareIcon());
            maximize = true;
        }
    }

    private void minimize() {
        animation.fadeOut(this, () -> setState(JFrame.ICONIFIED));
    }

    private void toggleSettings() {
        if (!morePopup) {
            morePopup = true;
            popupMore.show(btnMore, 0, btnMore.getHeight());
        }
        else {
            morePopup = false;
            popupMore.setVisible(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MoodyZApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> {
            new MoodyZApplication().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLayeredPane body;
    private javax.swing.JPanel border;
    private com.techcircle.moodyz.app.views.components.global.CustomButton btnClose;
    private com.techcircle.moodyz.app.views.components.global.CustomButton btnMaximize;
    private com.techcircle.moodyz.app.views.components.global.CustomButton btnMinimize;
    private com.techcircle.moodyz.app.views.components.global.CustomButton btnMore;
    private com.techcircle.moodyz.app.views.components.InPlayingSong inPlayingSong;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenuItem itemNew;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private com.techcircle.moodyz.app.views.components.layouts.MainLayout mainLayout;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JPopupMenu popupMore;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
