package com.techcircle.moodyz.app.views.components.sidebar;

import com.techcircle.moodyz.app.views.components.global.RoundedPanel;
import com.techcircle.moodyz.utils.GUIStyler;
import com.techcircle.moodyz.utils.IconBuilder;
import net.miginfocom.swing.MigLayout;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;

import java.awt.*;

/**
 *
 * @author Gica Tran
 */
public class TopNav extends RoundedPanel {
    private GUIStyler guiStyler;

    /**
     * Creates new form TopNav
     */
    public TopNav() {
        super(20);
        initComponents();
        init();
    }

    private void init() {
        guiStyler = new GUIStyler();
        this.setLayout(new MigLayout("wrap, fill", "25[]25", "15[grow]10[grow]15"));

        this.remove(btnHome);
        this.remove(btnSearch);

        this.add(btnHome, "grow");
        this.add(btnSearch, "grow");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new com.techcircle.moodyz.app.views.components.global.CustomButton();
        btnSearch = new com.techcircle.moodyz.app.views.components.global.CustomButton();

        setBackground(new java.awt.Color(25, 25, 25));
        setMaximumSize(new java.awt.Dimension(350, 32767));
        setPreferredSize(new java.awt.Dimension(350, 130));

        btnHome.setBackground(new java.awt.Color(25, 25, 25));
        btnHome.setForeground(new java.awt.Color(128, 128, 128));
        btnHome.setIcon(new IconBuilder(FontAwesomeSolid.HOME, 22, Color.GRAY).prepareIcon()
        );
        btnHome.setText("Home");
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setFont(new java.awt.Font("Proxima Nova Rg", 1, 16)); // NOI18N
        btnHome.setHoverColor(new java.awt.Color(25, 25, 25));
        btnHome.setIconTextGap(15);
        btnHome.setPressedColor(new java.awt.Color(25, 25, 25));
        btnHome.setTextAlignment(2);

        btnSearch.setBackground(new java.awt.Color(25, 25, 25));
        btnSearch.setForeground(new java.awt.Color(128, 128, 128));
        btnSearch.setIcon(new IconBuilder(FontAwesomeSolid.SEARCH, 22, Color.GRAY).prepareIcon()
        );
        btnSearch.setText("Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFont(new java.awt.Font("Proxima Nova Rg", 1, 16)); // NOI18N
        btnSearch.setHoverColor(new java.awt.Color(25, 25, 25));
        btnSearch.setIconTextGap(15);
        btnSearch.setPressedColor(new java.awt.Color(25, 25, 25));
        btnSearch.setTextAlignment(2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.techcircle.moodyz.app.views.components.global.CustomButton btnHome;
    private com.techcircle.moodyz.app.views.components.global.CustomButton btnSearch;
    // End of variables declaration//GEN-END:variables
}
